'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class VisitHistoryEntities
    Inherits DbContext

    Public Sub New()
        'MyBase.New("name=VisitHistoryEntities")
        MyBase.New(ConfigClass.Config("VisitHistoryEntities"))
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function SP_SELECT_FINISHED_VISIT(rep_id As String, month As Nullable(Of Integer), year As Nullable(Of Integer)) As ObjectResult(Of SP_SELECT_FINISHED_VISIT_Result)
        Dim rep_idParameter As ObjectParameter = If(rep_id IsNot Nothing, New ObjectParameter("rep_id", rep_id), New ObjectParameter("rep_id", GetType(String)))

        Dim monthParameter As ObjectParameter = If(month.HasValue, New ObjectParameter("month", month), New ObjectParameter("month", GetType(Integer)))

        Dim yearParameter As ObjectParameter = If(year.HasValue, New ObjectParameter("year", year), New ObjectParameter("year", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_SELECT_FINISHED_VISIT_Result)("SP_SELECT_FINISHED_VISIT", rep_idParameter, monthParameter, yearParameter)
    End Function

End Class
